In [15]:
import numpy as np

In [16]:
pylist = list(range(1000))

In [17]:
nparray = np.arange(1000)

In [18]:
print(pylist[:20])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


In [19]:
print(nparray[:20])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [20]:
%time for _ in range(100) : [item*3 for item in pylist]

CPU times: user 5.48 ms, sys: 40 μs, total: 5.52 ms
Wall time: 5.3 ms


In [22]:
%time for _ in range(100) : nparray = nparray*3

CPU times: user 1.9 ms, sys: 1.81 ms, total: 3.71 ms
Wall time: 2.56 ms


In [24]:
mat=np.zeros((2,5))

In [25]:
mat

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [39]:
mat.dtype

dtype('float64')

In [40]:
mat1=np.ones((2,5))

In [41]:
mat1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [42]:
mat3=np.empty((4,5))


In [43]:
mat3

array([[3.60519386e-315, 0.00000000e+000, 0.00000000e+000,
        2.50521045e-292, 4.35468375e-282],
       [1.13254994e-017, 0.00000000e+000, 0.00000000e+000,
        1.23452218e-123, 0.00000000e+000],
       [0.00000000e+000, 5.30697755e-313, 5.68922526e-013,
        1.92664875e-157, 3.72849093e-008],
       [1.93447287e-157, 1.60137455e+002, 1.06401622e+007,
        1.81606340e-287, 4.32105981e-306]])

# playing with array

In [60]:
arr2=np.array([3,4,6,7,12,3])

In [61]:
arr2

array([ 3,  4,  6,  7, 12,  3])

In [62]:
arr=arr2[4:6]

In [63]:
arr

array([12,  3])

I changed array but array 2 got changed cz its being interpreted in c (as numpy is coded in c) and c had pointers and arr is not a copy but an instance of arr2.

In [64]:
arr[0]=9

In [65]:
arr2

array([3, 4, 6, 7, 9, 3])

In [66]:
arr3=arr2[4:6].copy()

In [67]:
arr3

array([9, 3])

In [68]:
arr3[0]=9

In [69]:
arr3

array([9, 3])