In [1]:
import numpy as np

In [2]:
pylist = list(range(1000))

In [3]:
nparray = np.arange(1000)

In [4]:
print(pylist[:20])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


In [5]:
print(nparray[:20])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [6]:
%time for _ in range(100) : [item*3 for item in pylist]

CPU times: user 1.34 ms, sys: 0 ns, total: 1.34 ms
Wall time: 1.35 ms


In [7]:
%time for _ in range(100) : nparray = nparray*3

CPU times: user 301 μs, sys: 52 μs, total: 353 μs
Wall time: 437 μs


In [8]:
mat=np.zeros((2,5))

In [9]:
mat

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
mat.dtype

dtype('float64')

In [11]:
mat1=np.ones((2,5))

In [12]:
mat1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
mat3=np.empty((4,5))


In [14]:
mat3

array([[4.71119676e-316, 0.00000000e+000, 1.17360744e-236,
        5.18741137e-313, 5.57615717e-279],
       [4.65203811e+151, 2.95526650e-287, 1.15549302e-313,
        3.40062557e-309, 1.33360335e+241],
       [1.21929878e-310, 3.06836125e+257, 2.00414576e-312,
        1.81706500e-310, 5.32929927e-256],
       [2.50923972e-212, 4.16534737e-275, 6.76499388e-292,
        2.02633254e-315, 2.64480772e+180]])

# playing with array, slicing

In [15]:
arr2=np.array([3,4,6,7,12,3])

In [16]:
arr2

array([ 3,  4,  6,  7, 12,  3])

In [17]:
arr=arr2[4:6]

In [18]:
arr

array([12,  3])

I changed array but array 2 got changed cz its being interpreted in c (as numpy is coded in c) and c had pointers and arr is not a copy but an instance of arr2.

In [19]:
arr[0]=9

In [20]:
arr2

array([3, 4, 6, 7, 9, 3])

In [21]:
arr3=arr2[4:6].copy()

In [22]:
arr3

array([9, 3])

In [23]:
arr3[0]=9

In [24]:
arr3

array([9, 3])

# axing sorting

numpy has two axis 0 and 1 

0 being y axis and 1 being x (or 0 vertical and 1 horizontal)

In [26]:
a = np.array([[1,3,6],
             [7,12,34]])

In [27]:
a.sum(axis = 0)

array([ 8, 15, 40])

In [28]:
b = np.array([[12,22,45],
              [54,66,73]])

In [29]:
np.cross(a,b)

array([[    3,    27,   -14],
       [-1368,  1325,  -186]])

In [32]:
np.dot(a,b.transpose())

array([[ 348,  690],
       [1878, 3652]])

In [47]:
%%time
np.sort((np.cross(a,b)), (axis := 0),kind = 'mergesort')

CPU times: user 143 μs, sys: 18 μs, total: 161 μs
Wall time: 166 μs


array([[-1368,    27,  -186],
       [    3,  1325,   -14]])

In [48]:
%%time
np.sort((np.cross(a,b)), (axis := 0),kind = 'qicksort')

CPU times: user 60 μs, sys: 8 μs, total: 68 μs
Wall time: 69.4 μs


array([[-1368,    27,  -186],
       [    3,  1325,   -14]])

In [49]:
%%time
np.sort((np.cross(a,b)), (axis := 0),kind = 'heapsort')

CPU times: user 90 μs, sys: 12 μs, total: 102 μs
Wall time: 105 μs


array([[-1368,    27,  -186],
       [    3,  1325,   -14]])

# arrange and argsort